---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-deployment
  labels:
    app: redmine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
      namespace: default
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: key1
        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: key1
        - name: REDMINE_DB_USERNAME 
          value: "pg-user"
        - name: REDMINE_DB_DATABASE
          value: "pg-database"
        - name: REDMINE_DB_POSTGRES
          value: "database"

      hostNetwork: true


